---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-adapter-http-vertx
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-adapter-http-vertx
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
    nodePort: 30080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
    nodePort: 30443
  selector:
    app: hono-adapter-http-vertx
    group: {{ .Values.project.groupId }}
  {{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" )}}
  type: LoadBalancer
  {{- else}}
  type: NodePort
  {{- end}}
