---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amqp-messaging-network
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: ${hono.amqp-network.service}-ext
spec:
  ports:
  - name: amqps
    port: 15671
    protocol: TCP
    targetPort: amqps
    nodePort: 30671
  - name: amqp
    port: 15672
    protocol: TCP
    targetPort: amqp
    nodePort: 30672
  selector:
    app: amqp-messaging-network
    role: router
    group: {{ .Values.project.groupId }}
  {{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" )}}
  type: LoadBalancer
  {{- else}}
  type: NodePort
  {{- end}}
