---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-adapter-amqp-vertx
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-adapter-amqp-vertx
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
    nodePort: 32672
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
    nodePort: 32671
  selector:
    app: hono-adapter-amqp-vertx
    group: {{ .Values.project.groupId }}
  {{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" )}}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end}}
